import json
from pathlib import Path
from graphify.validate import validate_extraction

f01 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Consulta_Direta_TJRJ_15_09_2026.txt"
f02 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Detalhes_HC_e_ROC_TJRJ_13_08_2026.txt"
f03 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Espelho_HC_TJRJ_0029845_Completo.txt"
f04 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Espelho_HC_TJRJ_0029845_Completo_05_09_2026.html"
f05 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Recurso_Ordinario_ROC_00580_TJRJ.html"
f06 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\03_HABEAS_CORPUS_2A_INSTANCIA_TJRJ\Recurso_Ordinario_ROC_00580_TJRJ.txt"
f07 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_Analises_e_Estrategias\Debate_Adversarial_Julio_Pereira_Marcos_20260908.md"
f08 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_Analises_e_Estrategias\Debate_Adversarial_Julio_Pereira_Marcos_Peticao_DrGabriel.md"
f09 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_Analises_e_Estrategias\Subsidios_Estrategicos_Advocacia_Julio_STJ.pdf"
f10 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\Aditamento_Fato_Novo_Excesso_Prazo_Dr_Gabriel.pdf"
f11 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\01_Decisoes\2026-07-31_Decisao_Liminar_Min_Herman_Benjamin_Texto.txt"
f12 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\01_Decisoes\Decisao_HermanBenjamin_Raw.html"
f13 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\01_Decisoes\2026-07-31_Decisao_Liminar_Min_Herman_Benjamin.pdf"
f14 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Consulta_Direta_STJ_05_09_2026.txt"
f15 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Consulta_Direta_STJ_15_09_2026.txt"
f16 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Consulta_Direta_STJ_22_08_2026.txt"
f17 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Espelho_STJ_HC_1116750_05_09_2026.html"
f18 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\STJ_HC_1116750_Fases_Consolidadas.md"
f19 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Ultima_Fase_Registrada_STJ.txt"
f20 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\02_Fases_e_Andamentos\Verificacao_STJ_ROC_03_08_2026.txt"
f21 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\03_Peticoes_e_Pareceres\2026-08-13_Manifestacao_Ministerial_68200_2026_MPF_STJ_HC_1116750.md"
f22 = r"C:\Projetos\superJus\Clientes\Júlio_Pereira_Marcos\04_RECURSOS_SUPERIORES_STJ\03_Peticoes_e_Pareceres\Relatorio_Comparativo_Docling.md"

s01 = "03_habeas_corpus_2a_instancia_tjrj_consulta_direta_tjrj_15_09_2026"
s02 = "03_habeas_corpus_2a_instancia_tjrj_detalhes_hc_e_roc_tjrj_13_08_2026"
s03 = "03_habeas_corpus_2a_instancia_tjrj_espelho_hc_tjrj_0029845_completo"
s04 = "03_habeas_corpus_2a_instancia_tjrj_espelho_hc_tjrj_0029845_completo_05_09_2026"
s05 = "03_habeas_corpus_2a_instancia_tjrj_recurso_ordinario_roc_00580_tjrj"
s06 = "03_habeas_corpus_2a_instancia_tjrj_recurso_ordinario_roc_00580_tjrj"
s07 = "04_analises_e_estrategias_debate_adversarial_julio_pereira_marcos_20260908"
s08 = "04_analises_e_estrategias_debate_adversarial_julio_pereira_marcos_peticao_drgabriel"
s09 = "04_analises_e_estrategias_subsidios_estrategicos_advocacia_julio_stj"
s10 = "04_recursos_superiores_stj_aditamento_fato_novo_excesso_prazo_dr_gabriel"
s11 = "04_recursos_superiores_stj_01_decisoes_2026_07_31_decisao_liminar_min_herman_benjamin_texto"
s12 = "04_recursos_superiores_stj_01_decisoes_decisao_hermanbenjamin_raw"
s13 = "04_recursos_superiores_stj_01_decisoes_2026_07_31_decisao_liminar_min_herman_benjamin"
s14 = "04_recursos_superiores_stj_02_fases_e_andamentos_consulta_direta_stj_05_09_2026"
s15 = "04_recursos_superiores_stj_02_fases_e_andamentos_consulta_direta_stj_15_09_2026"
s16 = "04_recursos_superiores_stj_02_fases_e_andamentos_consulta_direta_stj_22_08_2026"
s17 = "04_recursos_superiores_stj_02_fases_e_andamentos_espelho_stj_hc_1116750_05_09_2026"
s18 = "04_recursos_superiores_stj_02_fases_e_andamentos_stj_hc_1116750_fases_consolidadas"
s19 = "04_recursos_superiores_stj_02_fases_e_andamentos_ultima_fase_registrada_stj"
s20 = "04_recursos_superiores_stj_02_fases_e_andamentos_verificacao_stj_roc_03_08_2026"
s21 = "04_recursos_superiores_stj_03_peticoes_e_pareceres_2026_08_13_manifestacao_ministerial_68200_2026_mpf_stj_hc_1116750"
s22 = "04_recursos_superiores_stj_03_peticoes_e_pareceres_relatorio_comparativo_docling"

nodes = [
    # File 01: Consulta Direta TJRJ 15/09/2026
    {
        "id": f"{s01}_doc",
        "label": "Consulta Direta TJRJ (15/09/2026) - HC 0029845-67.2026.8.19.0000",
        "file_type": "document",
        "source_file": f01,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-15T09:19:00",
        "author": "Tribunal de Justiça do Estado do Rio de Janeiro",
        "contributor": None,
    },
    {
        "id": f"{s01}_hc_tjrj_0029845",
        "label": "Habeas Corpus TJRJ nº 0029845-67.2026.8.19.0000",
        "file_type": "concept",
        "source_file": f01,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s01}_setima_camara_criminal",
        "label": "7ª Câmara Criminal do TJRJ",
        "file_type": "concept",
        "source_file": f01,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s01}_des_sidney_rosa_da_silva",
        "label": "Desembargador Sidney Rosa da Silva (Relator TJRJ)",
        "file_type": "concept",
        "source_file": f01,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s01}_arquivamento_definitivo",
        "label": "Arquivamento Definitivo do HC no TJRJ (20/08/2026)",
        "file_type": "concept",
        "source_file": f01,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-20T16:55:00",
        "author": None,
        "contributor": None,
    },

    # File 02: Detalhes HC e ROC TJRJ 13/08/2026
    {
        "id": f"{s02}_doc",
        "label": "Detalhes HC e ROC TJRJ (13/08/2026)",
        "file_type": "document",
        "source_file": f02,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-13T01:11:00",
        "author": "Tribunal de Justiça do Estado do Rio de Janeiro",
        "contributor": None,
    },
    {
        "id": f"{s02}_remessa_2vp_recurso_ordinario",
        "label": "Remessa do HC à 2ª Vice-Presidência para Recurso Ordinário (28/07/2026)",
        "file_type": "concept",
        "source_file": f02,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-28T17:45:00",
        "author": None,
        "contributor": None,
    },

    # File 03: Espelho HC TJRJ 0029845 Completo
    {
        "id": f"{s03}_doc",
        "label": "Espelho Processual Completo HC e ROC TJRJ 0029845",
        "file_type": "document",
        "source_file": f03,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": "Tribunal de Justiça do Estado do Rio de Janeiro",
        "contributor": None,
    },
    {
        "id": f"{s03}_duplicidade_registral_tjrj",
        "label": "Duplicidade Registral no TJRJ (HC 2026.059.10770 e ROC 2026.141.00580)",
        "file_type": "concept",
        "source_file": f03,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 04: Espelho HC TJRJ Completo 05/09/2026 (HTML 404)
    {
        "id": f"{s04}_doc",
        "label": "Erro 404 / Página de Manutenção Portal TJRJ (05/09/2026)",
        "file_type": "document",
        "source_file": f04,
        "source_location": None,
        "source_url": "https://www.tjrj.jus.br",
        "captured_at": "2026-09-05",
        "author": "Portal TJRJ",
        "contributor": None,
    },
    {
        "id": f"{s04}_indisponibilidade_portal_tjrj",
        "label": "Indisponibilidade Temporária do Sistema de Consulta TJRJ",
        "file_type": "concept",
        "source_file": f04,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 05: Recurso Ordinario ROC 00580 TJRJ (HTML)
    {
        "id": f"{s05}_html_doc",
        "label": "Página Web do Recurso Ordinário Constitucional ROC 2026.141.00580 TJRJ",
        "file_type": "document",
        "source_file": f05,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-21T09:10:00",
        "author": "Tribunal de Justiça do Estado do Rio de Janeiro",
        "contributor": None,
    },

    # File 06: Recurso Ordinario ROC 00580 TJRJ (TXT)
    {
        "id": f"{s06}_txt_doc",
        "label": "Andamento Processual do ROC nº 2026.141.00580 TJRJ",
        "file_type": "document",
        "source_file": f06,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-21T09:10:00",
        "author": "Tribunal de Justiça do Estado do Rio de Janeiro",
        "contributor": None,
    },
    {
        "id": f"{s06}_baixa_definitiva_2vp",
        "label": "Baixa Definitiva do ROC da 2VP para a 7ª Câmara Criminal (20/08/2026)",
        "file_type": "concept",
        "source_file": f06,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-20T14:33:00",
        "author": None,
        "contributor": None,
    },

    # File 07: Debate Adversarial Julio Pereira Marcos 20260908
    {
        "id": f"{s07}_doc",
        "label": "Relatório do Comitê Jurídico Adversarial (08/09/2026)",
        "file_type": "document",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-08T17:49:36",
        "author": "Comitê Jurídico SuperJus",
        "contributor": None,
    },
    {
        "id": f"{s07}_tese_art_580_cpp_isonomia",
        "label": "Tese de Extensão da Liberdade Provisória com Corréus (Art. 580 CPP)",
        "file_type": "rationale",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s07}_tese_excesso_prazo_art_400",
        "label": "Tese de Relaxamento por Excesso de Prazo sem AIJ (Art. 400 CPP)",
        "file_type": "rationale",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s07}_tese_gravidade_abstrata_contemporaneidade",
        "label": "Tese de Nulidade por Falta de Contemporaneidade e Gravidade Abstrata",
        "file_type": "rationale",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s07}_tese_descaracterizacao_art_35_delegado",
        "label": "Tese de Descaracterização do Art. 35 pela Confissão do Delegado Nelson Esquiba",
        "file_type": "rationale",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s07}_tese_confronto_vocalico",
        "label": "Tese de Nulidade por Ausência de Exame de Confronto Vocálico (STJ HC 262.971/RJ)",
        "file_type": "rationale",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s07}_filtro_realismo_minuta_blindada",
        "label": "Filtro Estratégico de Realismo para a Minuta Blindada ao Min. Og Fernandes",
        "file_type": "concept",
        "source_file": f07,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 08: Debate Adversarial Peticao Dr Gabriel
    {
        "id": f"{s08}_doc",
        "label": "Confronto Adversarial Real: Petição Dr. Gabriel vs. Parecer MPF nº 68200-2026",
        "file_type": "document",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-08T19:49:12",
        "author": "Comitê Jurídico SuperJus",
        "contributor": None,
    },
    {
        "id": f"{s08}_dr_gabriel_alves_guimaraes",
        "label": "Dr. Gabriel Alves Guimarães (OAB/RJ 203.902)",
        "file_type": "concept",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s08}_subprocurador_mario_ferreira_leite",
        "label": "Subprocurador-Geral da República Dr. Mário Ferreira Leite (MPF)",
        "file_type": "concept",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s08}_nulidade_decisao_duas_linhas",
        "label": "Nulidade Absoluta da Decisão de Piso (2 linhas per relationem / Art. 315 §2º CPP)",
        "file_type": "rationale",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s08}_desconstituicao_tese_foragido_bnmp",
        "label": "Desconstituição da Pecha de Foragido por Inexistência de Cadastro no BNMP",
        "file_type": "rationale",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s08}_erro_genero_minuta_mpf",
        "label": "Erro Material da Minuta Ministerial do MPF (Cuidados Maternos / Art. 318 IV CPP)",
        "file_type": "concept",
        "source_file": f08,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 09: Subsidios Estrategicos Advocacia Julio STJ
    {
        "id": f"{s09}_doc",
        "label": "Subsídios Estratégicos & Inteligência Processual - Defesa Técnica STJ",
        "file_type": "document",
        "source_file": f09,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-09",
        "author": "SuperJus Inteligência Processual",
        "contributor": None,
    },
    {
        "id": f"{s09}_alerta_aposentadoria_og_fernandes",
        "label": "Alerta Regimental de Aposentadoria Compulsória do Min. Og Fernandes (Nov/2026)",
        "file_type": "concept",
        "source_file": f09,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s09}_flancos_vulneraveis_mpf",
        "label": "Mapeamento dos Flancos Vulneráveis do Parecer Ministerial MPF",
        "file_type": "rationale",
        "source_file": f09,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 10: Aditamento Fato Novo Excesso Prazo Dr Gabriel
    {
        "id": f"{s10}_doc",
        "label": "Petição de Aditamento por Fato Novo - Excesso de Prazo de 117 Dias (Dr. Gabriel)",
        "file_type": "document",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-07",
        "author": "Gabriel Alves Guimarães",
        "contributor": None,
    },
    {
        "id": f"{s10}_fato_novo_117_dias_sem_aij",
        "label": "Fato Novo Superveniente: 117 Dias Ininterruptos de Cárcere sem AIJ",
        "file_type": "concept",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s10}_paralisacao_2_vara_buzios",
        "label": "Paralisação Processual de Mais de 33 Dias no Cartório da 2ª Vara de Búzios",
        "file_type": "concept",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s10}_stj_hc_840122_sp",
        "label": "Precedente STJ HC 840.122/SP (Excesso de Prazo por Inércia Exclusiva do Estado)",
        "file_type": "concept",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s10}_stj_hc_798690_sc",
        "label": "Precedente STJ HC 798.690/SC (Extensão do Art. 580 CPP por Excesso de Prazo)",
        "file_type": "concept",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s10}_stj_hc_457303_to",
        "label": "Precedente STJ HC 457.303/TO (Nulidade de Decisão de 2 Linhas per relationem)",
        "file_type": "concept",
        "source_file": f10,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 11: Decisao Liminar Herman Benjamin (Texto)
    {
        "id": f"{s11}_doc",
        "label": "Decisão Liminar Monocrática Min. Herman Benjamin (Texto)",
        "file_type": "document",
        "source_file": f11,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-29T10:43:35",
        "author": "Ministro Herman Benjamin",
        "contributor": None,
    },
    {
        "id": f"{s11}_indeferimento_liminar_stj",
        "label": "Indeferimento Liminar Monocrático pelo Presidente Min. Herman Benjamin (29/07/2026)",
        "file_type": "concept",
        "source_file": f11,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-29T10:43:35",
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s11}_requisicao_informacoes_tjrj_buzios",
        "label": "Determinação de Requisição de Informações ao TJRJ e à 2ª Vara de Búzios",
        "file_type": "concept",
        "source_file": f11,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s11}_remessa_ao_mpf",
        "label": "Remessa dos Autos ao Ministério Público Federal para Parecer",
        "file_type": "concept",
        "source_file": f11,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 12: Decisao Herman Benjamin (Raw HTML)
    {
        "id": f"{s12}_doc",
        "label": "Decisão Liminar Min. Herman Benjamin - Código HTML Raw",
        "file_type": "document",
        "source_file": f12,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-29",
        "author": "Superior Tribunal de Justiça",
        "contributor": None,
    },

    # File 13: Decisao Liminar Herman Benjamin (PDF)
    {
        "id": f"{s13}_doc",
        "label": "Decisão Liminar Oficial em PDF Assinada Eletronicamente (Min. Herman Benjamin)",
        "file_type": "document",
        "source_file": f13,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-29T10:43:35",
        "author": "Ministro Herman Benjamin",
        "contributor": None,
    },

    # File 14: Consulta Direta STJ 05/09/2026 (Bloqueio CSID)
    {
        "id": f"{s14}_doc",
        "label": "Consulta Direta STJ Bloqueada por Desafio CSID (05/09/2026)",
        "file_type": "document",
        "source_file": f14,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-05T16:51:44",
        "author": "CSID/STJ",
        "contributor": None,
    },
    {
        "id": f"{s14}_bloqueio_csid_stj_05_09",
        "label": "Bloqueio de Consulta Web pela CSID/STJ (Desafio Cloudflare)",
        "file_type": "concept",
        "source_file": f14,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-05T16:51:44",
        "author": None,
        "contributor": None,
    },

    # File 15: Consulta Direta STJ 15/09/2026 (Erro pagina)
    {
        "id": f"{s15}_doc",
        "label": "Consulta Direta STJ - Erro de Página não Encontrada (15/09/2026)",
        "file_type": "document",
        "source_file": f15,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-15T09:19:56",
        "author": "CSID/STJ",
        "contributor": None,
    },

    # File 16: Consulta Direta STJ 22/08/2026
    {
        "id": f"{s16}_doc",
        "label": "Espelho de Consulta Processual STJ HC 1.116.750/RJ (22/08/2026)",
        "file_type": "document",
        "source_file": f16,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-22",
        "author": "Superior Tribunal de Justiça",
        "contributor": None,
    },
    {
        "id": f"{s16}_autuacao_hc_1116750",
        "label": "Autuação do HC 1.116.750/RJ no STJ em 27/07/2026",
        "file_type": "concept",
        "source_file": f16,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-07-27",
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s16}_conclusao_gabinete_og_fernandes",
        "label": "Conclusão ao Gabinete do Relator Min. Og Fernandes em 13/08/2026",
        "file_type": "concept",
        "source_file": f16,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-13T17:45:00",
        "author": None,
        "contributor": None,
    },

    # File 17: Espelho STJ HC 1116750 05/09/2026 (HTML)
    {
        "id": f"{s17}_doc",
        "label": "Página HTML com Desafio Cloudflare Turnstile CSID/STJ (05/09/2026)",
        "file_type": "document",
        "source_file": f17,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-05",
        "author": "CSID/STJ",
        "contributor": None,
    },

    # File 18: STJ HC 1116750 Fases Consolidadas
    {
        "id": f"{s18}_doc",
        "label": "Consolidação das 24 Fases Processuais do HC 1.116.750/RJ (STJ)",
        "file_type": "document",
        "source_file": f18,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-15T11:11:00",
        "author": "SuperJus Automação Forense",
        "contributor": None,
    },
    {
        "id": f"{s18}_superacao_antideteccao_playwright",
        "label": "Superação de Bloqueio Antibot do STJ via Playwright Antidetecção",
        "file_type": "concept",
        "source_file": f18,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s18}_sequencia_24_fases_stj",
        "label": "Trilha Temporal Completa das 24 Fases Processuais no STJ",
        "file_type": "concept",
        "source_file": f18,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 19: Ultima Fase Registrada STJ
    {
        "id": f"{s19}_doc",
        "label": "Registro da Última Fase no STJ: Conclusos ao Min. Og Fernandes",
        "file_type": "document",
        "source_file": f19,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-13T17:45:00",
        "author": "Superior Tribunal de Justiça",
        "contributor": None,
    },

    # File 20: Verificacao STJ ROC 03/08/2026
    {
        "id": f"{s20}_doc",
        "label": "Verificação de Homônimos e Autuação de Processos 1116750 no STJ (03/08/2026)",
        "file_type": "document",
        "source_file": f20,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-03",
        "author": "Superior Tribunal de Justiça",
        "contributor": None,
    },

    # File 21: Manifestacao Ministerial 68200-2026 MPF
    {
        "id": f"{s21}_doc",
        "label": "Manifestação Ministerial MPF nº 68200-2026 (Subprocurador Mário Ferreira Leite)",
        "file_type": "document",
        "source_file": f21,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-08-13T17:01:00",
        "author": "Mário Ferreira Leite",
        "contributor": None,
    },
    {
        "id": f"{s21}_preliminar_concomitancia_hc_roc",
        "label": "Tese Acusatória MPF: Inadmissibilidade por Concomitância entre HC e ROC",
        "file_type": "rationale",
        "source_file": f21,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s21}_imputacao_estado_fuga_4_anos",
        "label": "Tese Acusatória MPF: Justificação da Prisão por Suposto Estado de Fuga de 4 Anos",
        "file_type": "rationale",
        "source_file": f21,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s21}_inaplicabilidade_art_580_mpf",
        "label": "Tese Acusatória MPF: Inaplicabilidade da Extensão do Art. 580 CPP",
        "file_type": "rationale",
        "source_file": f21,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },

    # File 22: Relatorio Comparativo Docling
    {
        "id": f"{s22}_doc",
        "label": "Relatório Comparativo Docling: Parecer MPF vs. Petição Defesa STJ",
        "file_type": "document",
        "source_file": f22,
        "source_location": None,
        "source_url": None,
        "captured_at": "2026-09-02T18:10:17",
        "author": "SuperJus / IBM Docling",
        "contributor": None,
    },
    {
        "id": f"{s22}_tabela_confronto_teses",
        "label": "Tabela Analítica de Confronto Ponto a Ponto (Acusação Federal vs. Defesa Técnica)",
        "file_type": "concept",
        "source_file": f22,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
    {
        "id": f"{s22}_matriz_vulnerabilidades_acusacao",
        "label": "Matriz de Vulnerabilidades e Inconsistências Fáticas da Peça Ministerial",
        "file_type": "rationale",
        "source_file": f22,
        "source_location": None,
        "source_url": None,
        "captured_at": None,
        "author": None,
        "contributor": None,
    },
]

edges = [
    # File 01 internal edges
    {
        "source": f"{s01}_doc",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f01,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s01}_doc",
        "target": f"{s01}_setima_camara_criminal",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f01,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s01}_doc",
        "target": f"{s01}_des_sidney_rosa_da_silva",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f01,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s01}_doc",
        "target": f"{s01}_arquivamento_definitivo",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f01,
        "source_location": None,
        "weight": 1.0,
    },

    # File 02 internal & cross edges
    {
        "source": f"{s02}_doc",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f02,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s02}_doc",
        "target": f"{s02}_remessa_2vp_recurso_ordinario",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f02,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s02}_remessa_2vp_recurso_ordinario",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f02,
        "source_location": None,
        "weight": 1.0,
    },

    # File 03 internal & cross edges
    {
        "source": f"{s03}_doc",
        "target": f"{s03}_duplicidade_registral_tjrj",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f03,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s03}_duplicidade_registral_tjrj",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f03,
        "source_location": None,
        "weight": 1.0,
    },

    # File 04
    {
        "source": f"{s04}_doc",
        "target": f"{s04}_indisponibilidade_portal_tjrj",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f04,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s04}_indisponibilidade_portal_tjrj",
        "target": f"{s01}_doc",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.75,
        "source_file": f04,
        "source_location": None,
        "weight": 1.0,
    },

    # Files 05 & 06 (ROC 00580)
    {
        "source": f"{s05}_html_doc",
        "target": f"{s06}_txt_doc",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f05,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s06}_txt_doc",
        "target": f"{s06}_baixa_definitiva_2vp",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f06,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s06}_baixa_definitiva_2vp",
        "target": f"{s01}_arquivamento_definitivo",
        "relation": "semantically_similar_to",
        "confidence": "INFERRED",
        "confidence_score": 0.85,
        "source_file": f06,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s06}_txt_doc",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f06,
        "source_location": None,
        "weight": 1.0,
    },

    # File 07 (Debate Adversarial 20260908)
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_tese_art_580_cpp_isonomia",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_tese_excesso_prazo_art_400",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_tese_gravidade_abstrata_contemporaneidade",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_tese_descaracterizacao_art_35_delegado",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_tese_confronto_vocalico",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_doc",
        "target": f"{s07}_filtro_realismo_minuta_blindada",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s07}_tese_art_580_cpp_isonomia",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "rationale_for",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f07,
        "source_location": None,
        "weight": 1.0,
    },

    # File 08 (Debate Adversarial Dr Gabriel vs MPF)
    {
        "source": f"{s08}_doc",
        "target": f"{s08}_dr_gabriel_alves_guimaraes",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s08}_doc",
        "target": f"{s08}_subprocurador_mario_ferreira_leite",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s08}_doc",
        "target": f"{s08}_nulidade_decisao_duas_linhas",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s08}_doc",
        "target": f"{s08}_desconstituicao_tese_foragido_bnmp",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s08}_doc",
        "target": f"{s08}_erro_genero_minuta_mpf",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s08}_nulidade_decisao_duas_linhas",
        "target": f"{s07}_filtro_realismo_minuta_blindada",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.85,
        "source_file": f08,
        "source_location": None,
        "weight": 1.0,
    },

    # File 09 (Subsidios Estrategicos Advocacia)
    {
        "source": f"{s09}_doc",
        "target": f"{s09}_alerta_aposentadoria_og_fernandes",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f09,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s09}_doc",
        "target": f"{s09}_flancos_vulneraveis_mpf",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f09,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s09}_flancos_vulneraveis_mpf",
        "target": f"{s08}_erro_genero_minuta_mpf",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f09,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s09}_doc",
        "target": f"{s08}_dr_gabriel_alves_guimaraes",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f09,
        "source_location": None,
        "weight": 1.0,
    },

    # File 10 (Aditamento Fato Novo Excesso Prazo)
    {
        "source": f"{s10}_doc",
        "target": f"{s10}_fato_novo_117_dias_sem_aij",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_doc",
        "target": f"{s10}_paralisacao_2_vara_buzios",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_doc",
        "target": f"{s10}_stj_hc_840122_sp",
        "relation": "cites",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_doc",
        "target": f"{s10}_stj_hc_798690_sc",
        "relation": "cites",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_doc",
        "target": f"{s10}_stj_hc_457303_to",
        "relation": "cites",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_doc",
        "target": f"{s08}_dr_gabriel_alves_guimaraes",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_fato_novo_117_dias_sem_aij",
        "target": f"{s07}_tese_excesso_prazo_art_400",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_stj_hc_798690_sc",
        "target": f"{s07}_tese_art_580_cpp_isonomia",
        "relation": "rationale_for",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s10}_stj_hc_457303_to",
        "target": f"{s08}_nulidade_decisao_duas_linhas",
        "relation": "rationale_for",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f10,
        "source_location": None,
        "weight": 1.0,
    },

    # Files 11, 12, 13 (Decisao Herman Benjamin)
    {
        "source": f"{s11}_doc",
        "target": f"{s11}_indeferimento_liminar_stj",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f11,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s11}_doc",
        "target": f"{s11}_requisicao_informacoes_tjrj_buzios",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f11,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s11}_doc",
        "target": f"{s11}_remessa_ao_mpf",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f11,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s12}_doc",
        "target": f"{s11}_doc",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f12,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s13}_doc",
        "target": f"{s11}_doc",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f13,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s11}_indeferimento_liminar_stj",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f11,
        "source_location": None,
        "weight": 1.0,
    },

    # Files 14 & 15 & 17 (Consultas STJ e Bloqueios CSID)
    {
        "source": f"{s14}_doc",
        "target": f"{s14}_bloqueio_csid_stj_05_09",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f14,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s17}_doc",
        "target": f"{s14}_bloqueio_csid_stj_05_09",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f17,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s15}_doc",
        "target": f"{s14}_bloqueio_csid_stj_05_09",
        "relation": "semantically_similar_to",
        "confidence": "INFERRED",
        "confidence_score": 0.85,
        "source_file": f15,
        "source_location": None,
        "weight": 1.0,
    },

    # File 16 (Consulta Direta STJ 22/08/2026)
    {
        "source": f"{s16}_doc",
        "target": f"{s16}_autuacao_hc_1116750",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f16,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s16}_doc",
        "target": f"{s16}_conclusao_gabinete_og_fernandes",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f16,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s16}_autuacao_hc_1116750",
        "target": f"{s01}_hc_tjrj_0029845",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f16,
        "source_location": None,
        "weight": 1.0,
    },

    # File 18 (Fases Consolidadas STJ)
    {
        "source": f"{s18}_doc",
        "target": f"{s18}_superacao_antideteccao_playwright",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f18,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s18}_doc",
        "target": f"{s18}_sequencia_24_fases_stj",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f18,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s18}_superacao_antideteccao_playwright",
        "target": f"{s14}_bloqueio_csid_stj_05_09",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.85,
        "source_file": f18,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s18}_sequencia_24_fases_stj",
        "target": f"{s16}_autuacao_hc_1116750",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f18,
        "source_location": None,
        "weight": 1.0,
    },

    # File 19 (Ultima Fase Registrada STJ)
    {
        "source": f"{s19}_doc",
        "target": f"{s16}_conclusao_gabinete_og_fernandes",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f19,
        "source_location": None,
        "weight": 1.0,
    },

    # File 20 (Verificacao STJ ROC 03/08/2026)
    {
        "source": f"{s20}_doc",
        "target": f"{s16}_autuacao_hc_1116750",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f20,
        "source_location": None,
        "weight": 1.0,
    },

    # File 21 (Manifestacao Ministerial MPF)
    {
        "source": f"{s21}_doc",
        "target": f"{s08}_subprocurador_mario_ferreira_leite",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_doc",
        "target": f"{s21}_preliminar_concomitancia_hc_roc",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_doc",
        "target": f"{s21}_imputacao_estado_fuga_4_anos",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_doc",
        "target": f"{s21}_inaplicabilidade_art_580_mpf",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_doc",
        "target": f"{s16}_autuacao_hc_1116750",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_inaplicabilidade_art_580_mpf",
        "target": f"{s07}_tese_art_580_cpp_isonomia",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.85,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s21}_imputacao_estado_fuga_4_anos",
        "target": f"{s08}_desconstituicao_tese_foragido_bnmp",
        "relation": "conceptually_related_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f21,
        "source_location": None,
        "weight": 1.0,
    },

    # File 22 (Relatorio Comparativo Docling)
    {
        "source": f"{s22}_doc",
        "target": f"{s22}_tabela_confronto_teses",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f22,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s22}_doc",
        "target": f"{s22}_matriz_vulnerabilidades_acusacao",
        "relation": "references",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f22,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s22}_tabela_confronto_teses",
        "target": f"{s21}_doc",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f22,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s22}_tabela_confronto_teses",
        "target": f"{s10}_doc",
        "relation": "shares_data_with",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f22,
        "source_location": None,
        "weight": 1.0,
    },
    {
        "source": f"{s22}_matriz_vulnerabilidades_acusacao",
        "target": f"{s09}_flancos_vulneraveis_mpf",
        "relation": "semantically_similar_to",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f22,
        "source_location": None,
        "weight": 1.0,
    },
]

hyperedges = [
    {
        "id": "cadeia_recursal_habeas_corpus_tjrj_ao_stj",
        "label": "Cadeia Recursal e Conexão de Instâncias (TJRJ ao STJ)",
        "nodes": [
            f"{s01}_hc_tjrj_0029845",
            f"{s06}_baixa_definitiva_2vp",
            f"{s16}_autuacao_hc_1116750",
            f"{s11}_indeferimento_liminar_stj",
            f"{s16}_conclusao_gabinete_og_fernandes",
        ],
        "relation": "participate_in",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f01,
    },
    {
        "id": "triade_defensiva_soltura_imediata_stj",
        "label": "Tríade Defensiva de Soltura Imediata (Isonomia Art. 580 + Excesso 117 Dias + Nulidade Art. 315 §2º)",
        "nodes": [
            f"{s07}_tese_art_580_cpp_isonomia",
            f"{s10}_fato_novo_117_dias_sem_aij",
            f"{s08}_nulidade_decisao_duas_linhas",
        ],
        "relation": "form",
        "confidence": "INFERRED",
        "confidence_score": 0.95,
        "source_file": f10,
    },
    {
        "id": "confronto_dialetico_oficial_mpf_vs_defesa",
        "label": "Confronto Dialético Oficial Defesa Técnica vs. Ministério Público Federal",
        "nodes": [
            f"{s21}_doc",
            f"{s10}_doc",
            f"{s22}_tabela_confronto_teses",
            f"{s08}_desconstituicao_tese_foragido_bnmp",
        ],
        "relation": "participate_in",
        "confidence": "EXTRACTED",
        "confidence_score": 1.0,
        "source_file": f22,
    },
]

payload = {
    "nodes": nodes,
    "edges": edges,
    "hyperedges": hyperedges,
    "input_tokens": 0,
    "output_tokens": 0,
}

# Validation check
errors = validate_extraction(payload)
print(f"Validation errors count: {len(errors)}")
if errors:
    for e in errors:
        print("  ERROR:", e)
    raise SystemExit(1)

out_file = Path(r"C:\Projetos\superJus\graphify-out\.graphify_chunk_02.json")
out_file.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
print(f"Successfully generated {out_file.name} with {len(nodes)} nodes, {len(edges)} edges, {len(hyperedges)} hyperedges.")
